### ISSUE TITLE
not running with ruby-enterprise

### ISSUE THREAD

**Issue by L42y** [minad/pacgem#1]
$ pacgem cluster_management

/opt/ruby-enterprise/lib/ruby/site_ruby/1.8/rubygems/format.rb:19: uninitialized constant Gem::UserInteraction (NameError)
    from /opt/ruby-enterprise/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
    from /opt/ruby-enterprise/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in`require'
    from /usr/bin/pacgem:5

just upgrade pacgem-git

**Comment by minad** [comment]
Which version of ruby-enterprise are you using? I cannot reproduce this with the newest version from aur.

ruby 1.8.7 (2010-04-19 patchlevel 253) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2010.02

As you can see, it creates a package ruby-enterprise-cluster_management on my machine:

```
==> Resolving gems...
  -> cluster_management-0.5.1: Simple cluster management tools
==> Making package: ruby-enterprise-cluster_management 0.5.1-1 (Wed Feb  9 08:30:07 CET 2011)
==> Checking Runtime Dependencies...
==> Checking Buildtime Dependencies...
==> Retrieving Sources...
  -> Found cluster_management-0.5.1.gem
==> Validating source files with sha256sums...
    cluster_management-0.5.1.gem ... Passed
==> Extracting Sources...
==> Entering fakeroot environment...
==> Starting build()...
==> Installing gem...
Successfully installed cluster_management-0.5.1
1 gem installed
==> Fixing gem installation...
==> Tidying install...
  -> Purging other files...
  -> Compressing man and info pages...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Removing empty directories...
==> Creating package...
  -> Generating .PKGINFO file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: ruby-enterprise-cluster_management 0.5.1-1 (Wed Feb  9 08:30:09 CET 2011)
==> Checking ruby-enterprise-cluster_management-0.5.1-1-any.pkg.tar.xz with namcap...
ruby-enterprise-cluster_management W: Dependency included and not needed ('ruby-enterprise')
==> Installing ruby-enterprise-cluster_management-0.5.1-1-any.pkg.tar.xz with pacman...
```

**Comment by minad** [comment]
Thx for the report. 22965c3b8606a641b19e3b767aee1585866eea29 might fix this. Can you please debug this yourself a bit because I have problems reproducing the errors?

**Comment by L42y** [comment]
now it works, thanks for your great work

**Comment by minad** [comment]
finally :)

Thanks for testing! I would like to propose the tool as "standard" method to install ruby gems on arch. It works flawlessly for many gems on my machine and I find this better than cluttering whole aur with all those badly maintained ruby-\* packages. Any ideas on this? I am not sure if there are many people using ruby on arch. On gentoo there is a ruby team.
