### ISSUE TITLE
Stop pacgem from installing ruby-rake

### ISSUE THREAD

**Issue by ghost** [minad/pacgem#15]
It's included with the Ruby package in [extra], so, this breaks gems that require rake.

**Comment by minad** [comment]
@Undeterminant I wrote a fix to handle this problem. Please tell me if it works!

**Comment by ghost** [comment]
This seems to mark all of my packages as installed by `""`, so, probably needs a little tweaking.

**Comment by minad** [comment]
What do you mean by marked as "". For me it works.

**Comment by ghost** [comment]
It's preventing me from installing things globally that are already installed locally in my user directory as gems and then says `(Installed with )` when it's resolving gems instead of `(New)`.

**Comment by minad** [comment]
I fixed this. Could you please try again?

**Comment by ghost** [comment]
...it does work. Must have been some problem on my end. :/

**Comment by minad** [comment]
No wasn't. I made some fixes in the repository. Thank you for discovering this!

**Comment by ghost** [comment]
Hmm, after pulling the latest commit, the original bug is fixed, but `pacgem` seems to want to reinstall dependencies that have already been installed to the correct version. And `pacgem -u` seems to not even notice that said packages have been installed that weren't included with `ruby`.

**Comment by minad** [comment]
I released an updated version 0.9.10 which should fix these problems too. I hope everything works now as expected.

**Comment by minad** [comment]
And thanks for reporting the issues!
