### ISSUE TITLE
Creating symbolic link to existing license crashes

### ISSUE THREAD

**Issue by ghost** [minad/pacgem#17]
Some gems, rs-fsevent as an example, fail with the following error.

```
==> Installing license custom:ruby-rb-fsevent...
ln: failed to create symbolic link ‘/tmp/ruby-rb-fsevent/pkg/ruby-rb-fsevent/usr/share/licenses/ruby-rb-fsevent/LICENSE’: File exists
```

I overcame this by adding an "|| true" to the line in the PKGBUILD generator that does the symbolic links.

**Comment by ghost** [comment]
...I posted this exact issue an hour ago. See: #16.

**Comment by ghost** [comment]
Not identical, in your case the license didn't exist, in mine it already did.

```
 No such file or directory
```

vs 

```
File exists
```

**Comment by ghost** [comment]
I'm pretty sure that the error that you got was an incomplete fix for the bug that I got. Either way, they should be grouped together. :P

**Comment by ghost** [comment]
Sorry, my bad. I'll close this as duplicate.

**Comment by minad** [comment]
@rohitagr Could you please tell me the name of the failing gem?

**Comment by ghost** [comment]
"rb-fsevent" fails, but it was a common enough error. I think at least 5 of the dependencies of middleman failed for the same reason. I don't have access to my linux box right now, but tell me if you need more gems to reproduce the error.
