### ISSUE TITLE
Add option for --keep-version (working name)

### ISSUE THREAD

**Issue by ghost** [minad/pacgem#19]
Example: `pacgem --keep-version rails=3.2.13` or `pacgem -k rails=3.2.13` would create a `ruby-rails-3.2.13` package instead of just a `ruby-rails` package (and similarly named packages for any dependencies). This would make it easy to install multiple versions of different gems while still installing via pacgem.

**Comment by minad** [comment]
Multiple versions of the same gem are not possible in arch. For this we would have to include the version number in the package name, e.g. python2 vs python

**Comment by ghost** [comment]
That's what I was suggesting, though: add an option that would name packages with a version number so that you can install multiple versions of them.

**Comment by minad** [comment]
Hmm, I don't really like that but if you have a patch I would consider it.
