### ISSUE TITLE
Keep pacgem packages newer than AUR packages

### ISSUE THREAD

**Issue by ghost** [minad/pacgem#20]
This can be done by adding an epoch to PKGBUILD, so that revision number changes in AUR packages don't trigger an upgrade.

**Comment by runical** [comment]
It might also be an idea to change the package name to ruby-$GEMNAME-$VERSION if a gem needs a specific version that is not the latest. This way AUR packages might trigger upgrades, but there will be no major version upgrades like what happens now.

(Could be that this needs a new issue. If this is the case let me know, I'll open a new issue)

**Comment by minad** [comment]
I am not sure if I understand. Can you provide a patch?
