### ISSUE TITLE
Dependency conflict with AUR gem

### ISSUE THREAD

**Issue by papylhomme** [minad/pacgem#24]
Hello,

I have **ruby-tzinfo-1.2.2** installed using _pacgem_, and there is a new package update from the _AUR_ (tzinfo-1.2.2-2).

Problem is, when trying to update **tzinfo** with _AUR_, it pulls **ruby-thread_safe** as a dependency, but the gem is already installed as **ruby-thread-safe** by _pacgem_. 

Is there a special reason to replace '_' by '-' in the function **build_name** ?

**Comment by minad** [comment]
No, there is not. We should change that behaviour with the _-. You should also not use AUR and pacgem managed gems at the same time.

**Comment by papylhomme** [comment]
Yep, I used AUR for some gem before getting to know pacgem. Anyway, I updated to pacgem-git and made some reinstall ; with the new pkgrel addition yaourt doesn't disturb me anymore ;)

Problem solved as far as I'm concerned

Thanks for the quick answer !
