### ISSUE TITLE
dependencies with != should be changed to <>

### ISSUE THREAD

**Issue by worldwise001** [minad/pacgem#9]
Was following this guide:
https://wiki.archlinux.org/index.php/Redmine2_setup

I ran into an issue where sprockets required tilt != 1.3.0 (http://rubygems.org/gems/sprockets)
makepkg interprets this as "tilt!" = 1.3.0, meaning the tilt! package at version 1.3.0 which is wrong.

!= should be changed into <> when the dependencies are being set up in the PKGBUILD.

Unfortunately I don't have a patch to offer yet for pacgem, but may create one sometime soon.

**Comment by SjonHortensius** [comment]
I have actually attempted to fix this in https://github.com/minad/pacgem/commit/8aff60d1d3d58afe4ac1864abd9be0f71e3d21ac, did your version not include this change or didn't it work like expected?

**Comment by minad** [comment]
I just updated the package on aur

**Comment by minad** [comment]
@SjonHortensius : Btw. I added you to collaborators, you can push to my repository now if you want.

**Comment by SjonHortensius** [comment]
Yes I noticed, thanks!
